language: node_js
node_js: 8
branches:
  only: 
    - master
cache:
  directories:
    - "node_modules"
services:
  - docker
before_install:
  - docker run -d -p 54321:5432 mdillon/postgis
env:
  - DATABASE_URL="postgres://postgres@localhost:54321/postgres"
script:
  - yarn e2e
  - yarn test --integration --submitCoverage
  - yarn lint
